version: '3.6'

services:
  attack:
    container_name: ddev-${DDEV_SITENAME}-attack
    # comment out `image` and `entrypoint` in order to active
    image: 'tianon/true'
    entrypoint: "/true"
    # uncomment `build` in order to activate
    # build: 'attack'
    network_mode: 'host'
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - ATTACK_TYPE=bonesi
    ###
    # CAREFUL, CAREFUL, CAREFUL!
    # using real IP ranges will send TCP ACKS to REAL IP addresses
    # !!! either disable WAN network connection or ensure those packets are filtered !!!
    ###
      - ATTACK_BONESI_ADDRESSES=local-network.txt
      - ATTACK_HOST=http://$DDEV_HOSTNAME
      - ATTACK_HOST_CHECK=http://$DDEV_HOSTNAME/typo3
      - ATTACK_SERVICE=172.31.32.33
      - ATTACK_PACKETS=0
      - ATTACK_RATE=1
      - HTTP_EXPOSE=3000
    cap_add:
      - SYS_PTRACE
    volumes:
      - service-logs:/var/service-logs/

  ftp:
    container_name: ddev-${DDEV_SITENAME}-ftp
    # comment out `image` and `entrypoint` in order to active
    image: 'tianon/true'
    entrypoint: "/true"
    # uncomment `image` in order to activate
    # image: 'hauptmedia/proftpd:latest'
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - HTTP_EXPOSE=3000
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - FTP_USERNAME=uploader
      - FTP_PASSWORD=insecure
#    volumes:
#      - service-logs:/var/log

# notice: this can only be used once in running DDEV scenarios
  web:
    networks:
      default:
      attack-net:
        ipv4_address: 172.31.32.33
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN

volumes:
  service-logs:

networks:
  attack-net:
    ipam:
      driver: default
      config:
        - subnet: 172.31.32.0/24

