version: '3.6'

services:
  beef:
    container_name: ddev-${DDEV_SITENAME}-beef
    image: 'ilyaglow/beef:latest'
    ports:
      - 2000
      - 3000
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=3000
      - BEEF_USER=admin
      - BEEF_PASSWORD=joh316
